### ISSUE TITLE
Rename repo "all-of-me"

### ISSUE THREAD

**Issue by zefanja** [linuxmuster-docs/main#117]
We should rename the repo "all-of-me" to "main" or "docs".

@jollyzsher What do you think?

**Comment by jollyzsher** [comment]
sure. lets call it "main", ok?
does this affect any permanent links? In the wiki, i guess, sometimes in the forum.

anyway: lets do it.

**Comment by zefanja** [comment]
I guess we need to adjust in @readthedocs and @travis, too. Otherwise it should be fine.

**Comment by jollyzsher** [comment]
*  Managed to rename it, rename it in @readthedocs, @travis does not let me do it, but it still works, since all-of-me is rewritten to main.
* Managed to change the relevant parts in the docs itself in master and in v7 (via cherry-pick, ok?)
* updated-locales (a little unnecessary, no translation there)

**Comment by jollyzsher** [comment]
upgrade the repository: download new or use set-url
upgrade your fork:
`git remote set-url origin git@github.com:jollyzsher/main.git`
