### ISSUE TITLE
checklist rewrite

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster-docs/main#229]
a checklist like in v6.2
http://docs.linuxmuster.net/de/latest/systemadministration/install-from-scratch/preamble.html#checkliste

is nice-to-have, excluded for the time being not updated.

**Comment by toheine** [comment]
Jetzt unter diesem Link erreichbar:
https://docs.linuxmuster.net/de/v6/systemadministration/install-from-scratch/preamble.html?highlight=checkliste#checkliste

**Comment by toheine** [comment]
I can start with a checklist. But maybe we ask the support team which content and data they need in case of support. I can do this ... but I prefer a "go" from the doku-team ;-)

**Comment by MachtDochNix** [comment]
I had understood that the checklist should be for the person doing the installation. But it's a good idea to also have it available in case of support. I will suggest it to Alois and Holger.

**Comment by jolly-jump** [comment]
the checklist is for the admin / company installing linuxmuster.net for the first time.
Go ahead and also ask the support team, if you are uncertain.
you could also use the overview here: https://docs.linuxmuster.net/de/latest/getting-started/overview.html and declare this as a checklist.
Warum genau reden wir hier eigentlich englisch?

**Comment by toheine** [comment]
... because I want to improve my english ... ;-) ... ne ... ich hatte irgendwann Mal die Tage in die Runde gefragt: In meinen alten Notizen steht: Pull-Requests, Commits und Issues werden hier auf Englisch verfasst. Lieg ich da falsch?

**Comment by MachtDochNix** [comment]
Nein liegst du nicht, ich erinnere mich auch daran. Daher nutze ich auch intensiv deepl da ich kein Muttersprachler bin. Also meinetwegen können wir das gerne beibehalten. Einziger negativer Punkt der mir dazu einfällt, es könnte Leute wie mich abschrecken mich zu beteiligen. Daher poste ich jetzt mal beide Sprachen. 
Einmal getippt und zweimal Copy&Paste. :-)

No, you're not. I remember it too. That's why I use deepl intensively as I am not a native speaker. So for my sake we can keep it that way. The only negative point I can think of is that it might deter people like me from getting involved. So I post both languages now. 
Once typed and twice copy and paste. :-)

**Comment by cweikl** [comment]
is this still an issue ?

**Comment by MachtDochNix** [comment]
I don't think so, I would say it can be closed. It's no use for support, because people usually don't have something like that to hand in case of problems.

Only for the installation for newcomers it might be an advantage. 
You decide.

**Comment by cweikl** [comment]
I think we should close this issue, as we will rewrite the first part of the docs including an updated overview.
