### ISSUE TITLE
Rewrite from scratch documentation

### ISSUE THREAD

**Issue by zefanja** [linuxmuster-docs/main#422]
In the docs for a manual install of OPNSense our docs say, that you should select MBR mode. Why is this recommend over GPT Mode? Almost all other sources recommend GPT mode as default and MBR only old hardware / BIOS versions.

**Comment by cweikl** [comment]
From my point of view it is necessary to rewrite the from scratch part of the documentation. The above mentioned aspect is only one among others which have to be addressed.

**Comment by MachtDochNix** [comment]
:+1:

**Comment by thoschi** [comment]
Hi everyone,

Instead of opening a new issue, I add what I noted, when I tried to install v7 "from scratch". I hope this helps somehow.

First of all - it is incredible how much information is collected already. And I understand it is hard to maintain the different ways of installing linuxmuster. But - one may likely disagree - I consider that "from scratch" way the most important, as it is important to me to understand, what is going on in linuxmuster. I do not want to have a black box installed as quickly as possible with no idea what is "under the hood". My experience shows that it will leave me without any clue as soon as the first problem arises...

- on https://docs.linuxmuster.net/de/latest/getting-started/overview.html: it is somehow confusing (and sometimes even illustrated somehow inaccurate) that installing "from scratch" is "something else" than using virtualization. I'd rather distinguis "install by importing OVAs" and "install from scratch (on bare metal or any virtualization of your choice). There are already notes about this way (i.e. use Virtualbox >= 6), so this makes much more sense. When server specs are explained on the next page, this makes even more sense then (I used this to prepare my VMs - so all the information is there, its just that I felt to do something "unwanted" somehow).
- on https://docs.linuxmuster.net/de/latest/getting-started/overview.html: its good to explain the "follow me"-Button - but I'd remove the link to the picture
- nice to have: add "linuxmuster-server", "opnsense", ... to https://docs.linuxmuster.net/de/latest/_images/simple-network.png 
- https://docs.linuxmuster.net/de/latest/getting-started/installoptions/install-from-scratch/index.html: "Es steht zwei Hardware-Server" - first a typo and second I wonder, why there has to be 2 hardware-servers if another virtualization is possible. Better something like "Benötigt werden 2 Maschinen (Hardware oder virtuell), die über ein (virtuelles oder physisches) Netzwerk miteinander verbunden sind."
- ibid.: add the admin-pc to the requirements. "Eine weitere virtuelle oder reale Maschine (z.B. Ubuntu/Windows 10) steht als Admin-Rechner zur Verfügung). Btw. its a great idea to describe "what will be there"!
- https://docs.linuxmuster.net/de/latest/getting-started/installoptions/install-from-scratch/buildopnsense.html : I had a problem when installing from scratch, that the two network interfaces was switched after reboot. A remark like "Überprüfe, ob das LAN-Netz wirklich die range 192.168.1.1/24 besitzt. Ansonsten musst Du Dich anmelden und mit ... die Zuordnung ändern.
- ibid. "Für die Konfiguration...": an additional machine was already made a prerequisite. Better write sth. like "Hier kommt nun der Admin-PC ins Spiel..."
- https://docs.linuxmuster.net/de/latest/getting-started/installoptions/install-from-scratch/buildserver.html : "Falls Du Dich für das Netz der linuxmuster.net V6.2 entschieden hast... - I do not understand this remark. Is meant that I can use this to feel more familiar, is this necessary in any circumstances (for example if you plan to do a migration), are there reasons NOT to do this - at least there should be something like "Wir empfehlen dringend den v7-Standard (10.0.0.1), da dies der Regelfall in der Dokumentation sein wird."
- ibid. "Weiter geht es mit..." it is a little bit inconvinient to have the "next"-arrow and the "follow-me"-one on top of each other. You explained that before and probably there is no solution to this... but I'd think about using a separate "From Scratch"-Chapter (even if this sometimes doubles some work). Because...
- https://docs.linuxmuster.net/de/latest/getting-started/network/preliminarysettings/index.html here it gets confusing now. I do it from scratch but work with an "appliance"-script. And then I am asked to "Download/Import der VMs..." Thats just confusing :-) Actually I do not know enought about v7 to understand, what is going on here (dev-documentation pleaaase) and though it is okay to use a script I'd prefer a specific page that explains how this script works in a "from scratch" environment. Again: I find all the necessary information here! Its just about reorganizing a little bit in my eyes.
- ibid. "OPNSense Firewall": I'd think about another page for this. And for me this was important to change after my OPNsense-installation did not ended as documented. Here I could just continue. So maybe it makes sense to reorganize in a way, that from scratch I can add this chapter to the OPNsense-installation, do the Admin-PC configuration and continue with the server afterwards. I found this part of the documentation rather confusing.
- https://docs.linuxmuster.net/de/latest/getting-started/setup.html : add a remark on top that there are TWO ways how to do that (Schulkonsole OR Terminal). Also I'd encourage to change the header from "am Server" to sth like "an der Serverkonsole" or "via Terminal".
- ibid. I do not get the remark about "do-it-like-babo". "...gibt es den Begriff". What to do with this information besides knowing it :-)

- https://docs.linuxmuster.net/de/latest/getting-started/linuxclient.html I miss "from scratch" here. First of all this is explaining, how to download a linux-cloop. I would point that out clearly. If there is some time to do it, I'd add a visual somewhere explaining that there are 2 ways to get to a working client (again "from scratch" vs. "importing cloops prepared by others). 

- https://docs.linuxmuster.net/de/latest/clients/postsync/index.html To me it was nowhere clearly stated why I need the postsync-scripts for a working linux client. When I read the actual postsync-script it does a lot of things so far unwanted by me and definitely not necessary for becoming a domain member. Actually I see only the last part (adjusting the hostname) to be necessary. No idea if this holds true. Anyway on https://docs.linuxmuster.net/de/latest/clients/postsync/postsync-patchclasses.html there is suggested, that installing the package creates some folder structure under /srv/linbo/... - it did NOT do this on my server. I understand, that if they are created they do all the fancy stuff the postsync-script is doing - but it might be stated more clearly that this structure has to be created.

I lost some remarks not caring for my battery :-\ but I hope the one or other item might help making the documentation more clear when installing from scratch...

Best regards
Thomas

**Comment by MachtDochNix** [comment]
Hello, Thomas,

thank you for your comments, remarks and suggestions for improvement. As this issue shows, we also consider the description of this type of installation to be unfinished. But your contribution will help us to do so. 

To structure this work I have added checkboxes in your post. I noticed that a lot of subitems actually deserve an issue of their own.

We don't have any information about the dev-documentation, which could be installed easily.

For us the main focus is currently on the installation description and the explanation of the functions for the "superficial" work of the administrators, LuL and Sus.

As always: Help wanted!

Best regards 

Thorsten

**Comment by cweikl** [comment]
Hi Thomas,
thank you very much for your input. 

I have a question concerning your first item:
>on https://docs.linuxmuster.net/de/latest/getting-started/overview.html: it is somehow confusing (and sometimes even illustrated >somehow inaccurate) that installing "from scratch" is "something else" than using virtualization. I'd rather distinguis "install by >importing OVAs" and "install from scratch (on bare metal or any virtualization of your choice). There are already notes about this >way (i.e. use Virtualbox >= 6), so this makes much more sense. When server specs are explained on the next page, this makes >even more sense then (I used this to prepare my VMs - so all the information is there, its just that I felt to do something >"unwanted" somehow).

My understanding of "from scratch" is an installation directly on hardware (bare metal) without any virtualization ! This seems to differ from your point of view as for you this seems to imply hints for virtualization of your choice.
I am not sure that we would be able to support all these kind of installations / virtualization solutions. Maybe this is not yopur point, I am not sure.

We have a documentation for proxmox, xcp-ng and kvm. In addition, we intend to rewrite the  installation from scratch - directly on bare metal. Do you think, we should go for it as a bare metal one?

**Comment by thoschi** [comment]
Hi Chris,
indeed I would not necessarily "install from scratch" to bare metal. To download an OVA is some kind of "black box" to me - I do not know what has been done to "my" system and what has not then. Or when I read sth. like "in the old version of the OVA there was a mistake" (do I remember which one I got?)... So this is why I prefer to install myself. At the same time I see no advantage not to install into a virtualized machine (KVM in my case).
Actually this should not be a big deal - because installing "from scratch" should mostly be the same as installing on a bare metal machine. But I'd suggest to explicitly allow this way and keep the wording open to such ways (especially when explaining the network configuration).
I think, it should be easy to unite a bare-metal/from scratch-manual by just adding a few "boxes" explaining "if you do not install on bare metal but into a virtual machine, then...". Or the other way around "if installing on bare metal, just consider..."

So what I intended to say was that to me the opposite of installing "from scracth" is to "import OVAs". Because in the one case you do the work yourself (and need to know, what to do), in the other case you need to learn, how to import the OVAs and what to change afterwards.
As I wrote mostly the information is there already - I would just reorganize it concerning installing yourself or importing pre-installed OVAs.

I hope this is more clear now :+1: 
Best regards
Thomas

**Comment by MachtDochNix** [comment]
Hello Thomas,
hello Chris,

if I understand what Thomas wrote correctly, we are on the right track with the restructuring. Or do I see it wrong?

Kind regards

Thorsten

**Comment by mathiasrettich** [comment]
Hi,
I looked at the howto again and changed a few things:

- For me, "installing from scratch" is mainly intended for those who don't want to install a finished package. Quite frankly, I don't know anyone who doesn't virtually install a lmn.

~ I have removed the reference to 6.2 network. The subject will be taken up later.

~ Instead of MRB, I described GPT.

And I've also corrected a few linguistic mistakes.

Greeting,
Mathias

**Comment by cweikl** [comment]
Hi Mathias,
thank you very much for your revision of the chapter "from scratch". I will test and merge it.

@thoschi: Thanks for your clarifications. Now, I think we agreed to a common understanding for installing from scratch within a VM oder directly bare metal.

@MachtDochNix: Yes, you are right. Our discussed restructuring fits into thoschi's proposal.

Greetings,
Chris

**Comment by cweikl** [comment]
Please test the description as I added some further steps.
If it works, we should have a look at @thoschi issues which we have already addressed and which are still open. The open ones should lead to a new issue.

**Comment by mathiasrettich** [comment]
Hi there,
I played the installation completely on a Proxmox system. Everything went perfectly.
Greeting,
Mathias

**Comment by MachtDochNix** [comment]
Thanks to all for their work! Well done.
Can someone else look over the issue to see if everything has been worked through. If so we can close it.

**Comment by cweikl** [comment]
from our point of view we have finished with rewriting the chapter "from scratch". We have also tested in in different virtualization solutions (proxmox, xcp-ng).
Therefor, we close this issue.
There are still some substantial issues not fixed @thoschi indicated above. As these stand for their own, I created a new issue for them #506, #507, #508.
