### ISSUE TITLE
description setup Multicast-Server / linbo-remote / postsync etc. is missing

### ISSUE THREAD

**Issue by FreeInMind** [linuxmuster-docs/main#64]
https://www.linuxmuster.net/wiki/dokumentation:handbuch51:clients:linbo:multicast does not exist in new documentaion

Check http://docs.linuxmuster.net/de/latest/manuals/linbo/index.html vs. https://www.linuxmuster.net/wiki/dokumentation:handbuch51:clients:linbo:start

http://docs.linuxmuster.net/de/latest/howtos/linuxclients/rollout.html contains at bottom of page dead links

**Comment by jollyzsher** [comment]
Hi.
I would recommend to not include this in the main documentation.
Rather put it in a "techsheet" in the wiki: https://www.linuxmuster.net/wiki/dokumentation:techsheets:start

I know it is a main feature, but it is not the first thing to get the lmn running.
It would fit into the "manual" for linbo, but then again, if it (and a zillion other features) were to be described in the manual - it will be large again. I'm not sure if this is what we want.

**Comment by zefanja** [comment]
Are this docs meant to replace the wiki someday? IMHO we should have a simple "Getting started" guide (actually what we have now) but it would be nice if we could cover more advanced topics in the docs, too. 

We don't need to put in the LINBO manual, maybe just make a reference to a "adavanced linbo manual" or an attachment to the docs. On the other hand it could be included in the linbo manual because it belongs there. The first chapters could be a simple getting started thing, but then we can cover postsync, multicast, linbo-remote, ...

Just my 2ct :)

**Comment by jolly-jump** [comment]
This is an advanced topic. There is and always was the question where to handle those advanced topics.
Either in the main docs, which might bloat them, if really everything is documented.
Or in the developers github wiki (not really fitting)
or in the wiki - as a community documentation.

**Comment by cweikl** [comment]
I think we should close.
